export const interests = [
  {interest: 'Music', iconName: 'music'},
  {interest: 'Film', iconName: 'filmstrip'},
  {interest: 'Sports', iconName: 'basketball'},
  {interest: 'Fitness', iconName: 'dumbbell'},
  {interest: 'Travel', iconName: 'airplane'},
  {interest: 'Gaming', iconName: 'gamepad-square'},
  {interest: 'Tech', iconName: 'laptop'},
  {interest: 'Art', iconName: 'palette'},
  {interest: 'Literature', iconName: 'book-education'},
  {interest: 'Business', iconName: 'finance'},
  {interest: 'Nature', iconName: 'tree'},
  {interest: 'Culinary', iconName: 'chef-hat'},
  {interest: 'Politics', iconName: 'bullhorn'},
  {interest: 'Fashion', iconName: 'hanger'},
];
